---
# tasks file for pulp-rpm-prerequisites

- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- name: Add libmodulemd repo for Ubuntu
  apt_repository:
    repo: ppa:directhex/mock-dnf
  when:
    - ansible_distribution == "Ubuntu"
  become: true

- name: Install requested RPM packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages }}'
  become: true
