---
# tasks file for pulp-rpm-prereqs

- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- name: Install requested RPM packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages }}'
  become: true

- name: Merge rpm_prereq_pip_packages into prereq_pip_packages
  set_fact:
    prereq_pip_packages: "{{ prereq_pip_packages + rpm_prereq_pip_packages }}"
  when: rpm_prereq_pip_packages is defined
